version: '3'
services:
  db:
    image: mysql:5
    container_name: trackmania_db
    restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=consortiumRootDb
     - MYSQL_DATABASE=trackmania
     - MYSQL_USER=trackmania
     - MYSQL_PASSWORD=consortiumTrackmania
    volumes:
     - ./db-data:/var/lib/mysql
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: trackmania_phpmyadmin
    depends_on:
     - db
    environment:
     - PMA_HOST=db
    restart: always
    ports:
     - "8080:80"
  tmserver:
    build: ./docker-tmserver
    container_name: trackmania_tmserver
    depends_on:
     - db
    restart: always
    environment:
     - SERVER_LOGIN=pott_trupp
     - SERVER_LOGIN_PASSWORD=pott_trupp
     - SERVER_PORT=2350
     - SERVER_P2P_PORT=3450
     - SERVER_SA_PASSWORD=SuperAdminTrackmania
     - SERVER_ADM_PASSWORD=AdminTrackmania
     - SERVER_NAME=Trackmania Server
     - SERVER_COMMENT=This is a Trackmania Server
     - SERVER_PASSWORD=gtfo
    ports:
     - "2350:2350"
     - "2350:2350/udp"
     - "3450:3450"
     - "3450:3450/udp"
  xaseco:
    build: ./docker-xaseco
    container_name: trackmania_xaseco
    depends_on:
     - db
     - tmserver
    restart: on-failure
    environment:
     - SERVER_SA_PASSWORD=SuperAdminTrackmania
     - DB_HOST=db
     - DB_LOGIN=trackmania
     - DB_LOGIN_PASSWORD=consortiumTrackmania
     - DB_NAME=trackmania
